# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotiWorkshop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotiWorkshop

  target 'NotiWorkshop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotiWorkshopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.15.0'
